### PR TITLE
mark post as obsolete

### PR DESCRIPTION
**Pull request by derhuerst**
There's two posts on philosophy. You said the old one is obsolete anyways.

### CODE REVIEW

**Comment by derhuerst** [comment]
bump.

**Comment by derhuerst** [comment]
bump.

**Comment by derhuerst** [comment]
bump.

**Comment by derhuerst** [comment]
bump.

**Comment by derhuerst** [comment]
bump.

**Comment by derhuerst** [comment]
bump.

**Comment by derhuerst** [comment]
bump.

**Comment by derhuerst** [comment]
bump.

**Comment by derhuerst** [comment]
bump.

**Comment by derhuerst** [comment]
bump.

**Comment by derhuerst** [comment]
bump.

**Comment by derhuerst** [comment]
bump.

**Comment by derhuerst** [comment]
bump.

**Comment by stultiloquence** [comment]
Glad we figured this one out together.

**Pull request merged**
